//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BotClient.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No problem, enter the message now!.
        /// </summary>
        public static string EnterMessageNow {
            get {
                return ResourceManager.GetString("EnterMessageNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear friends, let&apos;s start a new giveaway!.
        /// </summary>
        public static string GiveawayAnnounce {
            get {
                return ResourceManager.GetString("GiveawayAnnounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just write the codeword `{0}` to participate..
        /// </summary>
        public static string GiveawayAnnounceKeyword {
            get {
                return ResourceManager.GetString("GiveawayAnnounceKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s start the next giveaway!.
        /// </summary>
        public static string GiveawayAnnounceNext {
            get {
                return ResourceManager.GetString("GiveawayAnnounceNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can win: **{0}**.
        /// </summary>
        public static string GiveawayAnnounceWin {
            get {
                return ResourceManager.GetString("GiveawayAnnounceWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In which languages do you wan&apos;t to announce the giveaway? Supported languages are: .
        /// </summary>
        public static string GiveawayAwardCultures {
            get {
                return ResourceManager.GetString("GiveawayAwardCultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        public static string GiveawayCongrats {
            get {
                return ResourceManager.GetString("GiveawayCongrats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter: %initgiveaway #[channel].
        /// </summary>
        public static string GiveawayEnterChannelTip {
            get {
                return ResourceManager.GetString("GiveawayEnterChannelTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To start now please enter the command: `%start`.
        /// </summary>
        public static string GiveawayEnterStart {
            get {
                return ResourceManager.GetString("GiveawayEnterStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tell me first when the giveaway should end..
        /// </summary>
        public static string GiveawayEnterTime {
            get {
                return ResourceManager.GetString("GiveawayEnterTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in repeat announcement: .
        /// </summary>
        public static string GiveawayErrorRepeat {
            get {
                return ResourceManager.GetString("GiveawayErrorRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating the timer. Giveaway failed to initialize..
        /// </summary>
        public static string GiveawayErrorTimer {
            get {
                return ResourceManager.GetString("GiveawayErrorTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `An awesome key code`.
        /// </summary>
        public static string GiveawayExamplePrize {
            get {
                return ResourceManager.GetString("GiveawayExamplePrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How often should the giveaway take place?.
        /// </summary>
        public static string GiveawayHowOften {
            get {
                return ResourceManager.GetString("GiveawayHowOften", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great, you finished initializing the giveaway!.
        /// </summary>
        public static string GiveawayInitialized {
            get {
                return ResourceManager.GetString("GiveawayInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very well, what&apos;s the key word users must reply, to participate in the raffle?.
        /// </summary>
        public static string GiveawayKeyword {
            get {
                return ResourceManager.GetString("GiveawayKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now enter the keyword, e.g. `giveaway!`.
        /// </summary>
        public static string GiveawayKeywordExample {
            get {
                return ResourceManager.GetString("GiveawayKeywordExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You missed to add the channel!.
        /// </summary>
        public static string GiveawayMissingChannel {
            get {
                return ResourceManager.GetString("GiveawayMissingChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start the giveaway before it is initialized..
        /// </summary>
        public static string GiveawayNotInitialized {
            get {
                return ResourceManager.GetString("GiveawayNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter e.g. `2` to repeate the event twice.
        /// </summary>
        public static string GiveawayOftenExample {
            get {
                return ResourceManager.GetString("GiveawayOftenExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The participation ends at {0}..
        /// </summary>
        public static string GiveawayParticipEndDate {
            get {
                return ResourceManager.GetString("GiveawayParticipEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The participation ends at {0}..
        /// </summary>
        public static string GiveawayParticipEndTime {
            get {
                return ResourceManager.GetString("GiveawayParticipEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK, which prize should be raffled?.
        /// </summary>
        public static string GiveawayPrize {
            get {
                return ResourceManager.GetString("GiveawayPrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter prize in language: {0} - e.g. {1}.
        /// </summary>
        public static string GiveawayPrizeExample {
            get {
                return ResourceManager.GetString("GiveawayPrizeExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giveaway was started!.
        /// </summary>
        public static string GiveawayStarted {
            get {
                return ResourceManager.GetString("GiveawayStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alright, let&apos;s start a new giveaway!.
        /// </summary>
        public static string GiveawayStartNew {
            get {
                return ResourceManager.GetString("GiveawayStartNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giveaway was canceled!.
        /// </summary>
        public static string GiveawayStopped {
            get {
                return ResourceManager.GetString("GiveawayStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give either a time, e.g. `20:00` (for today at 20:00 o&apos;clock), or date + time like e.g. `04/22/2019 20:00`.
        /// </summary>
        public static string GiveawayTimeExample {
            get {
                return ResourceManager.GetString("GiveawayTimeExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of course, the next raffle will take place at the following time: {0}.
        /// </summary>
        public static string GiveawayTimeResponse {
            get {
                return ResourceManager.GetString("GiveawayTimeResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again or enter `%cancel` to cancel the giveaway..
        /// </summary>
        public static string GiveawayTryAgain {
            get {
                return ResourceManager.GetString("GiveawayTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can enter `%cancel` at any moment, if you want to cancel the giveaway initiation!.
        /// </summary>
        public static string GiveawayTypeCancel {
            get {
                return ResourceManager.GetString("GiveawayTypeCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear friends, we got a winner:.
        /// </summary>
        public static string GiveawayWinner {
            get {
                return ResourceManager.GetString("GiveawayWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner was announced!.
        /// </summary>
        public static string GiveawayWinnerAnnounced {
            get {
                return ResourceManager.GetString("GiveawayWinnerAnnounced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , you won this prize:.
        /// </summary>
        public static string GiveawayWinnerPrize {
            get {
                return ResourceManager.GetString("GiveawayWinnerPrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not enter a list of cultures, e.g. `en` or `en, de`.
        /// </summary>
        public static string GiveawayWrongCulture {
            get {
                return ResourceManager.GetString("GiveawayWrongCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not enter a keyword, e.g. `giveaway!`.
        /// </summary>
        public static string GiveawayWrongKeyword {
            get {
                return ResourceManager.GetString("GiveawayWrongKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not enter a correct number, e.g. `2`.
        /// </summary>
        public static string GiveawayWrongOften {
            get {
                return ResourceManager.GetString("GiveawayWrongOften", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not enter a correct string, e.g. {0}.
        /// </summary>
        public static string GiveawayWrongPrize {
            get {
                return ResourceManager.GetString("GiveawayWrongPrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not entered a correct time format, e.g. `20: 00`.
        /// </summary>
        public static string GiveawayWrongTime {
            get {
                return ResourceManager.GetString("GiveawayWrongTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter e.g. `en` for english or enter `en, de` for english and german.
        /// </summary>
        public static string GiveawyAwardCulturesExample {
            get {
                return ResourceManager.GetString("GiveawyAwardCulturesExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good luck!.
        /// </summary>
        public static string GoodLuck {
            get {
                return ResourceManager.GetString("GoodLuck", resourceCulture);
            }
        }
    }
}
