//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BotClient.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No problem, enter the message now!.
        /// </summary>
        public static string EnterMessageNow {
            get {
                return ResourceManager.GetString("EnterMessageNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The giveaway initiation was canceled!.
        /// </summary>
        public static string GiveawayCanceled {
            get {
                return ResourceManager.GetString("GiveawayCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tell me first when the drawings should take place..
        /// </summary>
        public static string GiveawayEnterTime {
            get {
                return ResourceManager.GetString("GiveawayEnterTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alright, let&apos;s start a new giveaway!.
        /// </summary>
        public static string GiveawayStartNew {
            get {
                return ResourceManager.GetString("GiveawayStartNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give either a time, e.g. `20:00` (for today at 20:00 o&apos;clock), or date + time like e.g. `04/22/2019 20:00`.
        /// </summary>
        public static string GiveawayTimeExample {
            get {
                return ResourceManager.GetString("GiveawayTimeExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yout can enter `cancel` all the time if you want to cancel the giveaway intiation!.
        /// </summary>
        public static string GiveawayTypeCancel {
            get {
                return ResourceManager.GetString("GiveawayTypeCancel", resourceCulture);
            }
        }
    }
}
