//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BotClient.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No problem, enter the message now!.
        /// </summary>
        public static string EnterMessageNow {
            get {
                return ResourceManager.GetString("EnterMessageNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The giveaway initiation was canceled!.
        /// </summary>
        public static string GiveawayCanceled {
            get {
                return ResourceManager.GetString("GiveawayCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To start now please enter the command: `start`!.
        /// </summary>
        public static string GiveawayEnterStart {
            get {
                return ResourceManager.GetString("GiveawayEnterStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tell me first when the drawings should take place..
        /// </summary>
        public static string GiveawayEnterTime {
            get {
                return ResourceManager.GetString("GiveawayEnterTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How often should the Giveaway take place?.
        /// </summary>
        public static string GiveawayHowOften {
            get {
                return ResourceManager.GetString("GiveawayHowOften", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great, you finished initializing the giveaway!.
        /// </summary>
        public static string GiveawayInitialized {
            get {
                return ResourceManager.GetString("GiveawayInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very well, what&apos;s the key word to participate in the draw?.
        /// </summary>
        public static string GiveawayKeyword {
            get {
                return ResourceManager.GetString("GiveawayKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now enter the keyword, e.g. `giveaway!`.
        /// </summary>
        public static string GiveawayKeywordExample {
            get {
                return ResourceManager.GetString("GiveawayKeywordExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter e.g. `2` to repeate the event twice.
        /// </summary>
        public static string GiveawayOftenExample {
            get {
                return ResourceManager.GetString("GiveawayOftenExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK, which price should be raffled (in german)?.
        /// </summary>
        public static string GiveawayPrice {
            get {
                return ResourceManager.GetString("GiveawayPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And now please enter the price in english!.
        /// </summary>
        public static string GiveawayPriceEnglish {
            get {
                return ResourceManager.GetString("GiveawayPriceEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write e.g. `An awesome key code`!.
        /// </summary>
        public static string GiveawayPriceEnglishExample {
            get {
                return ResourceManager.GetString("GiveawayPriceEnglishExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, enter `Ein toller Key Code`!.
        /// </summary>
        public static string GiveawayPriceExample {
            get {
                return ResourceManager.GetString("GiveawayPriceExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alright, let&apos;s start a new giveaway!.
        /// </summary>
        public static string GiveawayStartNew {
            get {
                return ResourceManager.GetString("GiveawayStartNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give either a time, e.g. `20:00` (for today at 20:00 o&apos;clock), or date + time like e.g. `04/22/2019 20:00`.
        /// </summary>
        public static string GiveawayTimeExample {
            get {
                return ResourceManager.GetString("GiveawayTimeExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of course, the next draw will take place at the following time: {0}.
        /// </summary>
        public static string GiveawayTimeResponse {
            get {
                return ResourceManager.GetString("GiveawayTimeResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again or enter `cancel` to cancel the giveaway..
        /// </summary>
        public static string GiveawayTryAgain {
            get {
                return ResourceManager.GetString("GiveawayTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yout can enter `cancel` all the time if you want to cancel the giveaway intiation!.
        /// </summary>
        public static string GiveawayTypeCancel {
            get {
                return ResourceManager.GetString("GiveawayTypeCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast keine korrekte Zeichenfolge eingegeben, z.B. `giveaway!`.
        /// </summary>
        public static string GiveawayWrongKeyword {
            get {
                return ResourceManager.GetString("GiveawayWrongKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not enter a correct number, e.g. `2`.
        /// </summary>
        public static string GiveawayWrongOften {
            get {
                return ResourceManager.GetString("GiveawayWrongOften", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not enter a correct string, e.g. `Ein toller Key Code`.
        /// </summary>
        public static string GiveawayWrongPrice {
            get {
                return ResourceManager.GetString("GiveawayWrongPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not enter a correct string, e.g. `An awesome key code`.
        /// </summary>
        public static string GiveawayWrongPriceEnglish {
            get {
                return ResourceManager.GetString("GiveawayWrongPriceEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not entered a correct time format, e.g. `20: 00`.
        /// </summary>
        public static string GiveawayWrongTime {
            get {
                return ResourceManager.GetString("GiveawayWrongTime", resourceCulture);
            }
        }
    }
}
